// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   ViewModel.tt
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Controls=WPAppStudio.Controls;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;
using IServices=WPAppStudio.Services.Interfaces;
using IViewModels=WPAppStudio.ViewModel.Interfaces;
using Localization=WPAppStudio.Localization;
using Repositories=WPAppStudio.Repositories;
using Services=WPAppStudio.Services;
using ViewModelsBase=WPAppStudio.ViewModel.Base;
using WPAppStudio;
using WPAppStudio.Shared;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of ANIMATION_List ViewModel.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public partial class ANIMATION_ListViewModel : ViewModelsBase.VMBase, IViewModels.IANIMATION_ListViewModel
    {       

		private readonly IServices.IDialogService _dialogService;
		private readonly IServices.INavigationService _navigationService;
		private readonly IServices.ILockScreenService _lockScreenService;
		private readonly Repositories.IANIMATION_ANIMATION _aNIMATION_ANIMATION;
		private readonly Repositories.IThai_Thai _thai_Thai;
		private readonly Repositories.IINTER_INTER _iNTER_INTER;
		private readonly IServices.IInternetService _internetService;
		
        /// <summary>
        /// Initializes a new instance of the <see cref="ANIMATION_ListViewModel" /> class.
        /// </summary>
        /// <param name="dialogService">The Dialog Service.</param>
        /// <param name="navigationService">The Navigation Service.</param>
        /// <param name="lockScreenService">The Lock Screen Service.</param>
        /// <param name="aNIMATION_ANIMATION">The Animation_animation.</param>
        /// <param name="thai_Thai">The Thai_ Thai.</param>
        /// <param name="iNTER_INTER">The Inter_inter.</param>
        /// <param name="internetService">The Internet Service.</param>
        public ANIMATION_ListViewModel(IServices.IDialogService dialogService, IServices.INavigationService navigationService, IServices.ILockScreenService lockScreenService, Repositories.IANIMATION_ANIMATION aNIMATION_ANIMATION, Repositories.IThai_Thai thai_Thai, Repositories.IINTER_INTER iNTER_INTER, IServices.IInternetService internetService)
        {
			_dialogService = dialogService;
			_navigationService = navigationService;
			_lockScreenService = lockScreenService;
			_aNIMATION_ANIMATION = aNIMATION_ANIMATION;
			_thai_Thai = thai_Thai;
			_iNTER_INTER = iNTER_INTER;
			_internetService = internetService;
        }
		
	    /// <summary>
        /// IsInternetAvalaible property.
        /// </summary>		
        public Visibility IsInternetAvalaible
        {
	      get
          {
				return _internetService.IsNetworkAvailable() ? Visibility.Collapsed : Visibility.Visible; 
           }
		}
	
		private ObservableCollection<Entities.ANIMATIONSchema> _aNIMATION_ListListControlCollection;

        /// <summary>
        /// ANIMATION_ListListControlCollection property.
        /// </summary>		
        public ObservableCollection<Entities.ANIMATIONSchema> ANIMATION_ListListControlCollection
        {
            get
            {
				
                if(_aNIMATION_ListListControlCollection == null)
					_aNIMATION_ListListControlCollection = _aNIMATION_ANIMATION.GetData();
				return _aNIMATION_ListListControlCollection;     
            }
            set
            {
                SetProperty(ref _aNIMATION_ListListControlCollection, value);
            }
        }
	
		private int _aNIMATION_ListListControlCollectionPageNumber;

        /// <summary>
        /// ANIMATION_ListListControlCollectionPageNumber property.
        /// </summary>		
        public int ANIMATION_ListListControlCollectionPageNumber
        {
            get
            {
				return _aNIMATION_ListListControlCollectionPageNumber;
            }
            set
            {
                SetProperty(ref _aNIMATION_ListListControlCollectionPageNumber, value);
            }
        }
	
		private Entities.ANIMATIONSchema _selectedANIMATION_ListListControlCollection;

        /// <summary>
        /// SelectedANIMATION_ListListControlCollection property.
        /// </summary>		
        public Entities.ANIMATIONSchema SelectedANIMATION_ListListControlCollection
        {
            get
            {
				return _selectedANIMATION_ListListControlCollection;
            }
            set
            {
                _selectedANIMATION_ListListControlCollection = value;
                if (value != null)
                    _navigationService.NavigateTo<IViewModels.IANIMATION_DetailViewModel>(_selectedANIMATION_ListListControlCollection);
            }
        }
	
		private ObservableCollection<Entities.ThaiSchema> _thai_ListListControlCollection;

        /// <summary>
        /// Thai_ListListControlCollection property.
        /// </summary>		
        public ObservableCollection<Entities.ThaiSchema> Thai_ListListControlCollection
        {
            get
            {
				
                if(_thai_ListListControlCollection == null)
					_thai_ListListControlCollection = _thai_Thai.GetData();
				return _thai_ListListControlCollection;     
            }
            set
            {
                SetProperty(ref _thai_ListListControlCollection, value);
            }
        }
	
		private int _thai_ListListControlCollectionPageNumber;

        /// <summary>
        /// Thai_ListListControlCollectionPageNumber property.
        /// </summary>		
        public int Thai_ListListControlCollectionPageNumber
        {
            get
            {
				return _thai_ListListControlCollectionPageNumber;
            }
            set
            {
                SetProperty(ref _thai_ListListControlCollectionPageNumber, value);
            }
        }
	
		private Entities.ThaiSchema _selectedThai_ListListControlCollection;

        /// <summary>
        /// SelectedThai_ListListControlCollection property.
        /// </summary>		
        public Entities.ThaiSchema SelectedThai_ListListControlCollection
        {
            get
            {
				return _selectedThai_ListListControlCollection;
            }
            set
            {
                _selectedThai_ListListControlCollection = value;
                if (value != null)
                    _navigationService.NavigateTo<IViewModels.IThai_DetailViewModel>(_selectedThai_ListListControlCollection);
            }
        }
	
		private ObservableCollection<Entities.INTERSchema> _iNTER_ListListControlCollection;

        /// <summary>
        /// INTER_ListListControlCollection property.
        /// </summary>		
        public ObservableCollection<Entities.INTERSchema> INTER_ListListControlCollection
        {
            get
            {
				
                if(_iNTER_ListListControlCollection == null)
					_iNTER_ListListControlCollection = _iNTER_INTER.GetData();
				return _iNTER_ListListControlCollection;     
            }
            set
            {
                SetProperty(ref _iNTER_ListListControlCollection, value);
            }
        }
	
		private int _iNTER_ListListControlCollectionPageNumber;

        /// <summary>
        /// INTER_ListListControlCollectionPageNumber property.
        /// </summary>		
        public int INTER_ListListControlCollectionPageNumber
        {
            get
            {
				return _iNTER_ListListControlCollectionPageNumber;
            }
            set
            {
                SetProperty(ref _iNTER_ListListControlCollectionPageNumber, value);
            }
        }
	
		private Entities.INTERSchema _selectedINTER_ListListControlCollection;

        /// <summary>
        /// SelectedINTER_ListListControlCollection property.
        /// </summary>		
        public Entities.INTERSchema SelectedINTER_ListListControlCollection
        {
            get
            {
				return _selectedINTER_ListListControlCollection;
            }
            set
            {
                _selectedINTER_ListListControlCollection = value;
                if (value != null)
                    _navigationService.NavigateTo<IViewModels.IINTER_DetailViewModel>(_selectedINTER_ListListControlCollection);
            }
        }

        /// <summary>
        /// Delegate method for the GetANIMATION_ListListControlCollectionCommand command.
        /// </summary>
        public  void GetANIMATION_ListListControlCollectionCommandDelegate(int pageNumber= 0) 
        {
				GetANIMATION_ListListControlCollectionData(pageNumber);
        }
		

        private ICommand _getANIMATION_ListListControlCollectionCommand;

        /// <summary>
        /// Gets the GetANIMATION_ListListControlCollectionCommand command.
        /// </summary>
        public ICommand GetANIMATION_ListListControlCollectionCommand
        {
            get { return _getANIMATION_ListListControlCollectionCommand = _getANIMATION_ListListControlCollectionCommand ?? new ViewModelsBase.DelegateCommand<int>(GetANIMATION_ListListControlCollectionCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the GetThai_ListListControlCollectionCommand command.
        /// </summary>
        public  void GetThai_ListListControlCollectionCommandDelegate(int pageNumber= 0) 
        {
				GetThai_ListListControlCollectionData(pageNumber);
        }
		

        private ICommand _getThai_ListListControlCollectionCommand;

        /// <summary>
        /// Gets the GetThai_ListListControlCollectionCommand command.
        /// </summary>
        public ICommand GetThai_ListListControlCollectionCommand
        {
            get { return _getThai_ListListControlCollectionCommand = _getThai_ListListControlCollectionCommand ?? new ViewModelsBase.DelegateCommand<int>(GetThai_ListListControlCollectionCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the GetINTER_ListListControlCollectionCommand command.
        /// </summary>
        public  void GetINTER_ListListControlCollectionCommandDelegate(int pageNumber= 0) 
        {
				GetINTER_ListListControlCollectionData(pageNumber);
        }
		

        private ICommand _getINTER_ListListControlCollectionCommand;

        /// <summary>
        /// Gets the GetINTER_ListListControlCollectionCommand command.
        /// </summary>
        public ICommand GetINTER_ListListControlCollectionCommand
        {
            get { return _getINTER_ListListControlCollectionCommand = _getINTER_ListListControlCollectionCommand ?? new ViewModelsBase.DelegateCommand<int>(GetINTER_ListListControlCollectionCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the SetLockScreenCommand command.
        /// </summary>
        public  void SetLockScreenCommandDelegate() 
        {
				_lockScreenService.SetLockScreen("DoWapp-Splashscreen-WXGA-black.png");
        }
		

        private ICommand _setLockScreenCommand;

        /// <summary>
        /// Gets the SetLockScreenCommand command.
        /// </summary>
        public ICommand SetLockScreenCommand
        {
            get { return _setLockScreenCommand = _setLockScreenCommand ?? new ViewModelsBase.DelegateCommand(SetLockScreenCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the AboutCommand command.
        /// </summary>
        public  void AboutCommandDelegate() 
        {
				_navigationService.NavigateTo<IViewModels.IAboutViewModel>();
        }
		

        private ICommand _aboutCommand;

        /// <summary>
        /// Gets the AboutCommand command.
        /// </summary>
        public ICommand AboutCommand
        {
            get { return _aboutCommand = _aboutCommand ?? new ViewModelsBase.DelegateCommand(AboutCommandDelegate); }
        }

        private void GetANIMATION_ListListControlCollectionData(int pageNumber = 0)
        {
				ANIMATION_ListListControlCollectionPageNumber = pageNumber;

                if (pageNumber == 0)
				{
					var items = _aNIMATION_ANIMATION.GetData(pageNumber);
                    ANIMATION_ListListControlCollection = items;
				}
                else   
				{
					var items = _aNIMATION_ANIMATION.GetData(pageNumber);
                    foreach (var item in items)                    
                        ANIMATION_ListListControlCollection.Add(item);
				}
		}

        private void GetThai_ListListControlCollectionData(int pageNumber = 0)
        {
				Thai_ListListControlCollectionPageNumber = pageNumber;

                if (pageNumber == 0)
				{
					var items = _thai_Thai.GetData(pageNumber);
                    Thai_ListListControlCollection = items;
				}
                else   
				{
					var items = _thai_Thai.GetData(pageNumber);
                    foreach (var item in items)                    
                        Thai_ListListControlCollection.Add(item);
				}
		}

        private void GetINTER_ListListControlCollectionData(int pageNumber = 0)
        {
				INTER_ListListControlCollectionPageNumber = pageNumber;

                if (pageNumber == 0)
				{
					var items = _iNTER_INTER.GetData(pageNumber);
                    INTER_ListListControlCollection = items;
				}
                else   
				{
					var items = _iNTER_INTER.GetData(pageNumber);
                    foreach (var item in items)                    
                        INTER_ListListControlCollection.Add(item);
				}
		}
    }
}
