// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// ANIMATION_List ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface IANIMATION_ListViewModel
    {		
	    /// <summary>
        /// IsInternetAvalaible property.
        /// </summary>		
        Visibility IsInternetAvalaible { get; }
        /// <summary>
        /// Gets/Sets the ANIMATION_ListListControlCollection property.
        /// </summary>
		ObservableCollection<Entities.ANIMATIONSchema> ANIMATION_ListListControlCollection { get; set; }
        /// <summary>
        /// Gets/Sets the ANIMATION_ListListControlCollectionPageNumber property.
        /// </summary>
		int ANIMATION_ListListControlCollectionPageNumber { get; set; }
        /// <summary>
        /// Gets/Sets the SelectedANIMATION_ListListControlCollection property.
        /// </summary>
		Entities.ANIMATIONSchema SelectedANIMATION_ListListControlCollection { get; set; }
        /// <summary>
        /// Gets/Sets the Thai_ListListControlCollection property.
        /// </summary>
		ObservableCollection<Entities.ThaiSchema> Thai_ListListControlCollection { get; set; }
        /// <summary>
        /// Gets/Sets the Thai_ListListControlCollectionPageNumber property.
        /// </summary>
		int Thai_ListListControlCollectionPageNumber { get; set; }
        /// <summary>
        /// Gets/Sets the SelectedThai_ListListControlCollection property.
        /// </summary>
		Entities.ThaiSchema SelectedThai_ListListControlCollection { get; set; }
        /// <summary>
        /// Gets/Sets the INTER_ListListControlCollection property.
        /// </summary>
		ObservableCollection<Entities.INTERSchema> INTER_ListListControlCollection { get; set; }
        /// <summary>
        /// Gets/Sets the INTER_ListListControlCollectionPageNumber property.
        /// </summary>
		int INTER_ListListControlCollectionPageNumber { get; set; }
        /// <summary>
        /// Gets/Sets the SelectedINTER_ListListControlCollection property.
        /// </summary>
		Entities.INTERSchema SelectedINTER_ListListControlCollection { get; set; }
        
        /// <summary>
        /// Gets the GetANIMATION_ListListControlCollectionCommand command.
        /// </summary>
		ICommand GetANIMATION_ListListControlCollectionCommand { get; }

        
        /// <summary>
        /// Gets the GetThai_ListListControlCollectionCommand command.
        /// </summary>
		ICommand GetThai_ListListControlCollectionCommand { get; }

        
        /// <summary>
        /// Gets the GetINTER_ListListControlCollectionCommand command.
        /// </summary>
		ICommand GetINTER_ListListControlCollectionCommand { get; }

        
        /// <summary>
        /// Gets the SetLockScreenCommand command.
        /// </summary>
		ICommand SetLockScreenCommand { get; }

        
        /// <summary>
        /// Gets the AboutCommand command.
        /// </summary>
		ICommand AboutCommand { get; }

	}
}
