// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// ANIMATION_Detail ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface IANIMATION_DetailViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentANIMATIONSchema property.
        /// </summary>
		Entities.ANIMATIONSchema CurrentANIMATIONSchema { get; set; }
        /// <summary>
        /// Gets/Sets the HasNextpanoramaANIMATION_Detail0 property.
        /// </summary>
		bool HasNextpanoramaANIMATION_Detail0 { get; set; }
        /// <summary>
        /// Gets/Sets the HasPreviouspanoramaANIMATION_Detail0 property.
        /// </summary>
		bool HasPreviouspanoramaANIMATION_Detail0 { get; set; }
        
        /// <summary>
        /// Gets the TextToSpeechANIMATION_DetailStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechANIMATION_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the ShareANIMATION_DetailStaticControlCommand command.
        /// </summary>
		ICommand ShareANIMATION_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartANIMATION_DetailStaticControlCommand command.
        /// </summary>
		ICommand PinToStartANIMATION_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the NextpanoramaANIMATION_Detail0 command.
        /// </summary>
		ICommand NextpanoramaANIMATION_Detail0 { get; }

        
        /// <summary>
        /// Gets the PreviouspanoramaANIMATION_Detail0 command.
        /// </summary>
		ICommand PreviouspanoramaANIMATION_Detail0 { get; }

	}
}
