// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// INTER_Detail ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface IINTER_DetailViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentINTERSchema property.
        /// </summary>
		Entities.INTERSchema CurrentINTERSchema { get; set; }
        /// <summary>
        /// Gets/Sets the HasNextpanoramaINTER_Detail0 property.
        /// </summary>
		bool HasNextpanoramaINTER_Detail0 { get; set; }
        /// <summary>
        /// Gets/Sets the HasPreviouspanoramaINTER_Detail0 property.
        /// </summary>
		bool HasPreviouspanoramaINTER_Detail0 { get; set; }
        
        /// <summary>
        /// Gets the TextToSpeechINTER_DetailStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechINTER_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the ShareINTER_DetailStaticControlCommand command.
        /// </summary>
		ICommand ShareINTER_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartINTER_DetailStaticControlCommand command.
        /// </summary>
		ICommand PinToStartINTER_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the NextpanoramaINTER_Detail0 command.
        /// </summary>
		ICommand NextpanoramaINTER_Detail0 { get; }

        
        /// <summary>
        /// Gets the PreviouspanoramaINTER_Detail0 command.
        /// </summary>
		ICommand PreviouspanoramaINTER_Detail0 { get; }

	}
}
