// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// Thai_Detail ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface IThai_DetailViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentThaiSchema property.
        /// </summary>
		Entities.ThaiSchema CurrentThaiSchema { get; set; }
        /// <summary>
        /// Gets/Sets the HasNextpanoramaThai_Detail0 property.
        /// </summary>
		bool HasNextpanoramaThai_Detail0 { get; set; }
        /// <summary>
        /// Gets/Sets the HasPreviouspanoramaThai_Detail0 property.
        /// </summary>
		bool HasPreviouspanoramaThai_Detail0 { get; set; }
        
        /// <summary>
        /// Gets the TextToSpeechThai_DetailStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechThai_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the ShareThai_DetailStaticControlCommand command.
        /// </summary>
		ICommand ShareThai_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartThai_DetailStaticControlCommand command.
        /// </summary>
		ICommand PinToStartThai_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the NextpanoramaThai_Detail0 command.
        /// </summary>
		ICommand NextpanoramaThai_Detail0 { get; }

        
        /// <summary>
        /// Gets the PreviouspanoramaThai_Detail0 command.
        /// </summary>
		ICommand PreviouspanoramaThai_Detail0 { get; }

	}
}
