// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IDataSource.tt
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;
using WPAppStudio.Shared;

namespace WPAppStudio.Repositories
{
    /// <summary>
    /// ANIMATION_ANIMATION interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface IANIMATION_ANIMATION
    {
		ObservableCollection<Entities.ANIMATIONSchema> GetData(int pageNumber = 0);
		ObservableCollection<Entities.ANIMATIONSchema> Search(FilterSpecification filter);
		bool HasPrevious(Entities.ANIMATIONSchema current);
		bool HasNext(Entities.ANIMATIONSchema current);
		Entities.ANIMATIONSchema Previous(Entities.ANIMATIONSchema current);
		Entities.ANIMATIONSchema Next(Entities.ANIMATIONSchema current);
    }
}
