// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IDataSource.tt
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;
using WPAppStudio.Shared;

namespace WPAppStudio.Repositories
{
    /// <summary>
    /// INTER_INTER interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface IINTER_INTER
    {
		ObservableCollection<Entities.INTERSchema> GetData(int pageNumber = 0);
		ObservableCollection<Entities.INTERSchema> Search(FilterSpecification filter);
		bool HasPrevious(Entities.INTERSchema current);
		bool HasNext(Entities.INTERSchema current);
		Entities.INTERSchema Previous(Entities.INTERSchema current);
		Entities.INTERSchema Next(Entities.INTERSchema current);
    }
}
