// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IDataSource.tt
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;
using WPAppStudio.Shared;

namespace WPAppStudio.Repositories
{
    /// <summary>
    /// Thai_Thai interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface IThai_Thai
    {
		ObservableCollection<Entities.ThaiSchema> GetData(int pageNumber = 0);
		ObservableCollection<Entities.ThaiSchema> Search(FilterSpecification filter);
		bool HasPrevious(Entities.ThaiSchema current);
		bool HasNext(Entities.ThaiSchema current);
		Entities.ThaiSchema Previous(Entities.ThaiSchema current);
		Entities.ThaiSchema Next(Entities.ThaiSchema current);
    }
}
