// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   DataSource.tt
using System;
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Globalization;
using System.Linq;
using System.Runtime.CompilerServices;
using Entities=WPAppStudio.Entities;
using RepositoriesBase=WPAppStudio.Repositories.Base;
using WPAppStudio.Shared;

namespace WPAppStudio.Repositories
{
    /// <summary>
    /// Thai_Thai data source.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public class Thai_Thai : IThai_Thai 
    {
		private const int MaxResults = 10;
        private readonly ObservableCollection<Entities.ThaiSchema> _data = new ObservableCollection<Entities.ThaiSchema>
		{
          new Entities.ThaiSchema
            {
                Id= new Guid("2a7b94c8-7c2c-4f99-8167-e0ccefb311d0"),
                Title=@" แหยมยโสธร 3 ",
                Subtitle=@"https://www.youtube.com/watch?v=hhhccA53YoM",
                Image=@"\Images\Item-8e633890-d9df-4ff2-b0fb-a6200b38aa37.jpg",
                Description=@" เวลาแห่งความสุขก็ได้ล่วงเลยผ่านฝน ผ่านหนาว ผ่านร้อนมาอีกหลายฤดู “บักแหยม” (หม่ำ จ๊กม๊ก) ผู้มีรักจริงกับ “เจ้ย” (เจเน็ต เขียว) สาวผู้รักมั่นคงมิเคยเสื่อมคลาย ลูกๆ ก็โตจนเรียนจบหรือไม่ก็ออกเรือนกันไปหมด เหลือแค่เพียง “คำผาน” (เพทาย วงษ์คำเหลา) ที่ยังเรียนไม่จบ ซ้ำชั้น ม.ศ.5 มาสามปี สร้างความระทึกใจให้กับกำนันแหยมและเจ้ยเรื่อยมา 

     จนกระทั่ง “คฑาเทพ” (ลิขิต บุตรพรม) ลูกชายอีกคนของกำนันแหยมกำลังจะเรียนจบกฎหมาย กลับมาเยี่ยมบ้านช่วงปิดเทอม ในระหว่างเดินทางกลับบ้านนั้นคฑาเทพก็ได้พบกับ “รำพัน” (อิงฟ้า เกตุคำ) หญิงสาวที่เดินทางกลับมาพร้อมกันโดยบังเอิญ และทั้งคู่ก็ตกหลุมรักกันตั้งแต่แรกเห็น ความรักของทั้งคู่คงจะผลิบานอย่างที่ควรจะเป็น หากแต่ว่า...รำพันดันเป็นลูกสาวคนโตของ “กำนันปอย” (เฉิน เชิญยิ้ม) เพื่อนรักเพื่อนแค้นในอดีตที่ไปแย่งแฟนเก่าของแหยมมา นั่นคือ “รำพึง” (เอ็นดู วงษ์คำเหลา) ซึ่งยังมี “รำเพย” (รัตติยาภรณ์ ภักดีล้น) ลูกสาวอีกคนที่เป็นถึงดาวประจำโรงเรียนที่คำผานดันตกหลุมรักเข้าให้อีก แล้วมีหรือที่คำผานจะพลาดการชิงชัยรักนี้  ",
			},
          new Entities.ThaiSchema
            {
                Id= new Guid("74c8217e-72e6-4ac2-9496-1d2e008417e5"),
                Title=@"https://www.youtube.com/watch?v=MTIjk8wPsbw",
                Subtitle=@"https://www.youtube.com/watch?v=M-FNNV1C1HA",
                Image=@"\Images\Item-5066b35a-dd05-4034-9deb-720eaadcdd82.jpg",
                Description=@"ฤดูร้อนนั้น…จอย (อาย-พิมพกานต์ แพร่คุณธรรม) เด็กสาวอนาคตสดใสในวงการบันเทิงโพสต์สเตตัสว่า ""อยากตาย"" สิงห์ (เก้า-จิรายุ ละอองมณี) หนุ่มหล่ออนาคตไกลอยากปลอบใจ จึงแอบขับรถพ่อมารับเธอกับเพื่อนสนิท มีน (ปันปัน-สุทัตตา อุดมศิลป์) โดยพาคู่หู กานต์ (สบาย-กฤษ สถาปนพิทักษ์กิจ) ไปเที่ยวทะเลด้วยกันเป็นครั้งแรก!!! แต่ค่ำคืนแห่งความสนุกกลับกลายเป็นคืนสยอง!!! เมื่อเกิดโศกนาฎกรรมไม่คาดฝันขึ้นคือ จอยตาย สิงห์ตัดสินใจซ่อนศพเพื่อให้คนที่ยังอยู่สามารถดำเนินชีวิตต่อไปได้ กานต์และมีนจึงต้องตกกระไดพลอยโจนไปด้วย แต่ผีจอยไม่ยอมให้ตัวเองถูกทิ้ง เมื่อมีนกลับไปโรงเรียน ผีจอยก็ตามติดไปสร้างความสะเทือนใจและเขย่าขวัญมีนอีก เพราะทั้งสองมีความลับซึ่งเพื่อนสนิทเท่านั้นที่รู้ และไม่เพียงเท่านั้น ผีจอยยังกลับไปที่บ้าน พบว่าน้องชายหรือ ติ่ง (เบสท์-เอกวัฒน์ เอกอัจฉริยา) กลายเป็นคนสำคัญของบ้านแทนเธอ เธอย่อมยอมไม่ได้ ผีจอยมีเรื่องอยากบอกกับคนเป็น แต่คนใกล้ชิดเธอ ไม่ว่าจะเป็นคนรัก เพื่อนสนิท และน้องชาย ล้วนไม่มีใครอยากรับรู้หรือจดจำ จนเป็นเหตุให้เกิดเรื่องราวระทึกขวัญที่เขย่าหัวใจของคนเคยเป็นวัยรุ่นทุกคน!? 
 ",
			},
          new Entities.ThaiSchema
            {
                Id= new Guid("73bd61eb-959a-4e5c-8772-b27924311d62"),
                Title=@"โลงจำนำ ",
                Subtitle=@"https://www.youtube.com/watch?v=MTIjk8wPsbw",
                Image=@"\Images\Item-20633b86-7ebc-4cca-8fca-c7c871b8d4d8.jpg",
                Description=@"หนังเรื่องนี้เป็นเรื่องราวของ คู่สามีภรรยา.. หนึ่ง (กฤษดา สุโกศล แคล์ป) มีอาชีพเป็นนักแต่งเพลง และ ดาว (ศุภักษร ไชยมงคล) ทั้งคู่ใช้ชีวิตอย่างเรียบง่ายใช้เงินเก็บที่มีอยู่เพื่อซื้อบ้าน ซื้อรถ และลงทุนเปิดผับเล็ก ๆ แต่ธุรกิจของเขาก็ไม่ได้เป็นไปตามที่หวัง 

     วันหนึ่ง... หนึ่งขับรถชนลูกเพื่อนบ้านที่สนิทสนมกันอย่างดี จนเด็กน้อยอาการโคม่าและนอนเป็นเจ้าหญิงนินทาไม่รู้ตัว ทั้งสองสามีภรรยาต้องร่วมกันชดใช้ในสิ่งที่เกิดขึ้น หนึ่งจึงตัดสินใจนำของเก่าที่มีอยู่ทั้งหมด ออกเดินทางไป ณ. โรงจำนำแห่งหนึ่ง 

    เมื่อไปถึง... มูลค่าสิ่งของที่เขานำมาไม่เพียงพอกับจำนวนเงินที่เขาต้องการ หลงจู้ เจ้าของโรงจำนำ ซึ่งเป็นคนที่มีความเชื่อเรื่องภูตผีวิญญาณ โดยมีการเซ่นไหว้ผีอยู่เป็นประจำ ได้เสนออีกหนึ่งทางเลือกให้กับหนึ่ง คือ ให้จำนำตัวเองกับผี!? 

    ในช่วงวิกฤตของชีวิต...เขาทั้งคู่ไม่มีทางให้เลือกมากนัก หนึ่งจึงตัดสินใจจำนำตัวเองกับผี เพื่อแลกกับเงิน 1 ล้านบาท โดยที่เค้าไม่อาจรู้เลยว่า จะได้พบเจอกับสิ่งใด ณ. โรงจำนำแห่งนี้!!!  ",
			},
		};
	
		
        /// <summary>
        /// Retrieves the data from a static data source, in an observable collection of ThaiSchema items.
        /// </summary>
        /// <returns>An observable collection of ThaiSchema items.</returns>
        public ObservableCollection<Entities.ThaiSchema> GetData(int numPage)
        {								
			return new ObservableCollection<Entities.ThaiSchema>(_data.Skip(MaxResults * numPage).Take(MaxResults));
        }
		
		/// <summary>
        /// Retrieves the data from a static data source, filtered by a filter specification, in an observable collection of ThaiSchema items.
        /// </summary>
		/// <param name="filter">Filter operation specification</param>
        /// <returns>An observable collection of ThaiSchema items.</returns>
        public ObservableCollection<Entities.ThaiSchema> Search(FilterSpecification filter)
        {
            return RepositoriesBase.Filter<Entities.ThaiSchema>.FilterCollection(filter, _data);
        }
		
		/// <summary>
        /// Checks if data source has a element before the passed as parameter
        /// </summary>
		/// <param name="current">Current element</param>
        /// <returns>True, if there is a previous element, false if there is not</returns>
		public bool HasPrevious(Entities.ThaiSchema current)
        {
            if (current == null || !_data.Any()) return false;

            return _data.IndexOf(current) > 0;
        }
		
		/// <summary>
        /// Checks if data source has a element after the passed as parameter
        /// </summary>
		/// <param name="current">Current element</param>
        /// <returns>True, if there is a next element, false if there is not</returns>
		public bool HasNext(Entities.ThaiSchema current)
        {
            if (current == null || !_data.Any()) return false;

            return _data.IndexOf(current) < _data.Count - 1;
        }
		
		/// <summary>
        /// Retrieves the previous element from source.
        /// </summary>
		/// <param name="current">Current element</param>
        /// <returns>The previous element from items, if it exists. Otherwise, returns null</returns>
        public Entities.ThaiSchema Previous(Entities.ThaiSchema current)
        {
            if (current == null || !_data.Any()) return null;

            if (_data.First().Equals(current)) return null;

            return _data[_data.IndexOf(current) - 1];
        }
		
		/// <summary>
        /// Retrieves the next element from source.
        /// </summary>
		/// <param name="current">Current element</param>
        /// <returns>The next element from items, if it exists. Otherwise, returns null</returns>
        public Entities.ThaiSchema Next(Entities.ThaiSchema current)
        {
            if (current == null || !_data.Any()) return null;

            if (_data.Last().Equals(current)) return null;

            return _data[_data.IndexOf(current) + 1];
        }
	}
}

